---
title: "Tutorials"
---

Below you will find a list of available tutorials with instructions on how to
install and use the tools we will be using in class. 

## Available Tutorials

- [01 - VSCode and Anaconda Tutorial](01-vscode-anaconda-tutorial.qmd)
- [02 - Jupyter Notebook and Markdown Tutorial](02-jupyter-markdown-tutorial.qmd)
- [03 - GitHub Tutorial](03-github-tutorial.qmd)
- [04 - PostgreSQL Tutorial](04-postgresql-tutorial.qmd)

PDF versions of the tutorials are also available on GitHub:
<https://github.com/danilofreire/qtm350/tree/main/tutorials>.

## Additional Resources

### Further examples

- [python-postgresql-example.ipynb](python-postgresql-example.ipynb): A Jupyter Notebook with a PostgreSQL example
- [testing-ipython.ipynb](testing-ipython.ipynb): A Jupyter Notebook for showing Markdown and code cells
- [testing-anaconda.py](testing-anaconda.py): A Python script for testing Anaconda installation

### Suggested Books

- [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
- [Elements of Data Science](https://allendowney.github.io/ElementsOfDataScience/README.html) by Allen Downey
- [SQL for Data Scientists](https://sqlfordatascientists.com/) by Renee M. P. Teate
- [Data Science on the Command Line](https://www.datascienceatthecommandline.com/) by Jeroen Janssens
- [Docker for Data Science](https://www.oreilly.com/library/view/docker-for-data/9781484230121/) by Joshua Cook
- [Pro Git](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub
- [Free programming books](https://github.com/EbookFoundation/free-programming-books)

### Online Courses

- [Coursera: Python for Everybody Specialisation](https://www.coursera.org/specializations/python)
- [edX: Python Basics for Data Science](https://www.edx.org/learn/python/ibm-python-basics-for-data-science)
- [Codecademy: Learn Python](https://www.codecademy.com/learn/learn-python-3)
- [DataCamp: Introduction to SQL](https://www.datacamp.com/courses/intro-to-sql-for-data-science)
- [Coursera: SQL for Data Science](https://www.coursera.org/learn/sql-for-data-science)
- [Coursera: Introduction to Git and GitHub](https://www.classcentral.com/course/introduction-git-github-18060)
- [Microsoft Learn: GitHub Copilot Fundamentals](https://learn.microsoft.com/en-us/training/paths/copilot/)

### Documentation

- [Official Python Documentation](https://docs.python.org/3/)
- [NumPy Documentation](https://numpy.org/doc/)
- [Pandas Documentation](https://pandas.pydata.org/docs/)
- [Matplotlib Documentation](https://matplotlib.org/stable/contents.html)
- [PostgreSQL Documentation](https://www.postgresql.org/docs/)
- [Git Documentation](https://git-scm.com/doc)
- [GitHub Documentation](https://docs.github.com/en)
- [Dask Documentation](https://docs.dask.org/en/latest/)
- [GitHub Co-Pilot Documentation](https://copilot.github.com/)
- [Docker Documentation](https://docs.docker.com/)

For any questions or issues regarding these tutorials, please [open a GitHub
issue](https://github.com/danilofreire/qtm350/issues), [submit a pull
request](https://github.com/danilofreire/qtm350/pulls), or [create a discussion
post](https://github.com/danilofreire/qtm350/discussions). 

Please do not forget that, in addition to the tutorials here, the [course
syllabus](https://danilofreire.github.io/qtm151/syllabus.html#course-outline-and-suggested-readings)
also contains a list of recommended weekly readings and additional resources.

I hope you like the
tutorials and find them useful! 
