---
title: Assignments
---

Here you will find information about the assignments for QTM 350. There are ten of them, each worth 5% of your final grade. The assignments are designed to help you practice the concepts covered in class and to develop your data science skills.

Assignment submissions are typically due on Wednesdays at 11:59pm in the week following their publication. You may submit via Canvas (preferred) or email (<danilo.freire@emory.edu>).

We encourage you to complete assignments in Jupyter Notebooks and submit them in PDF format. You can also submit them as a Word document, provided that code and results are included in the same document.

You will find the assignments in `.ipynb` format in the `assignments` folder on [the course repository](https://github.com/danilofreire/qtm350/tree/main/assignments). For your convenience, rendered versions are available on the course website; links are provided below.

When submitting, please name your files as follows: `assignment-01-your-name.pdf`. For instance: `assignment-01-john-doe.pdf`.

## Assignment Timeline

| Session | Topic | Assignment | Submission Deadline |
|---------|-------|------------|---------------------|
| 02 | [Computational Literacy](https://danilofreire.github.io/qtm350/lectures/lecture-02/02-computational-literacy.html) | [Assignment 01](https://github.com/danilofreire/qtm350/blob/main/assignments/01-assignment.ipynb) | 2025-01-29 |
| 03 | [Command Line Interface](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-03/03-command-line.html) | [Assignment 02](https://github.com/danilofreire/qtm350/blob/main/assignments/02-assignment.ipynb) | 2025-02-05 |
| 05 | [Version control with git and GitHub](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-05/05-git-github.html) | [Assignment 03](https://github.com/danilofreire/qtm350/blob/main/assignments/03-assignment.ipynb) | 2025-02-12 |
| 05 | [Version control with git and GitHub](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-05/05-git-github.html) | [Assignment 04](https://github.com/danilofreire/qtm350/blob/main/assignments/04-assignment.ipynb) | 2025-02-19 |
| 09 | [Writing Documents, Presentations, and Websites with Quarto](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-09/09-more-quarto.html) | [Assignment 05](https://github.com/danilofreire/qtm350/blob/main/assignments/05-assignment.ipynb) | 2025-02-26 |
| 12 | [AI-Assisted Programming with GitHub Copilot](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-12/12-copilot.html) | [Assignment 06](https://github.com/danilofreire/qtm350/blob/main/assignments/06-assignment.ipynb) | 2025-03-05 |
| 13 | [Python Data Types, Boolean Logic, and Control Structures.](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-13/13-python-intro.html#/title-slide) | [Assignment 07](https://github.com/danilofreire/qtm350/blob/main/assignments/07-assignment.ipynb) | 2025-03-19 |
| 15 | [Pandas](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-15/15-wrangling-aggregating.html) | [Assignment 08](https://github.com/danilofreire/qtm350/blob/main/assignments/08-assignment.ipynb) | 2025-03-26 |
| 18 | [SQLite and Python](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-18/18-sql-python.html) | [Assignment 09](https://github.com/danilofreire/qtm350/blob/main/assignments/09-assignment.sql) | 2025-04-02 |
| 21 | [Parallel Computing with Dask](https://raw.githack.com/danilofreire/qtm350/main/lectures/lecture-21/21-parallel-computing.html) | [Assignment 10](https://github.com/danilofreire/qtm350/blob/main/assignments/10-assignment.ipynb) | 2025-04-09 |

## In-Class Quizzes

In-class quizzes will be held on Wednesdays. They will be based on the material covered in the previous weeks. The quizzes will be open-book and open-notes, but you will not be allowed communicate with others during the quiz. They will also be available in the `assignment` folder on GitHub and on the course website.

* Quiz 01: <https://github.com/danilofreire/qtm350-quiz01>. 
* Quiz 02: <https://github.com/danilofreire/qtm350-quiz02>. 
* Quiz 03: <https://github.com/danilofreire/qtm350-quiz03>. 
* Quiz 04: <https://github.com/danilofreire/qtm350-quiz04>. 
* Quiz 05: <https://github.com/danilofreire/qtm350-quiz05>. 

## Final Project

The final project will be a group effort, with a maximum of 3 students per group. Detailed instructions are available on the GitHub repository: <https://github.com/danilofreire/qtm350/tree/main/project>.
